# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protos/helloworld.proto\x12\nhelloworld\":\n\x14PushEmailHashRequest\x12\x12\n\nemail_hash\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\"\'\n\x15PushEmailHashResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2c\n\x07Greeter\x12X\n\x0fpush_email_hash\x12 .helloworld.PushEmailHashRequest\x1a!.helloworld.PushEmailHashResponse\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_PUSHEMAILHASHREQUEST = _descriptor.Descriptor(
  name='PushEmailHashRequest',
  full_name='helloworld.PushEmailHashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email_hash', full_name='helloworld.PushEmailHashRequest.email_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server', full_name='helloworld.PushEmailHashRequest.server', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=97,
)


_PUSHEMAILHASHRESPONSE = _descriptor.Descriptor(
  name='PushEmailHashResponse',
  full_name='helloworld.PushEmailHashResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='helloworld.PushEmailHashResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['PushEmailHashRequest'] = _PUSHEMAILHASHREQUEST
DESCRIPTOR.message_types_by_name['PushEmailHashResponse'] = _PUSHEMAILHASHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushEmailHashRequest = _reflection.GeneratedProtocolMessageType('PushEmailHashRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHEMAILHASHREQUEST,
  '__module__' : 'protos.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PushEmailHashRequest)
  })
_sym_db.RegisterMessage(PushEmailHashRequest)

PushEmailHashResponse = _reflection.GeneratedProtocolMessageType('PushEmailHashResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUSHEMAILHASHRESPONSE,
  '__module__' : 'protos.helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PushEmailHashResponse)
  })
_sym_db.RegisterMessage(PushEmailHashResponse)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='push_email_hash',
    full_name='helloworld.Greeter.push_email_hash',
    index=0,
    containing_service=None,
    input_type=_PUSHEMAILHASHREQUEST,
    output_type=_PUSHEMAILHASHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
