# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/note.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/note.proto\x12\x04note\"\x1d\n\x0c\x42\x61seResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"F\n\x11\x43reateNoteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x11\n\tnote_type\x18\x03 \x01(\t\"U\n\x0f\x45\x64itNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x11\n\tnote_type\x18\x04 \x01(\t\"$\n\x11\x44\x65leteNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"e\n\x10UserNoteResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x11\n\tnote_type\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"\x15\n\x13GetUserNotesRequest\"Q\n\x14GetUserNotesResponse\x12*\n\nuser_notes\x18\x01 \x03(\x0b\x32\x16.note.UserNoteResponse\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x83\x02\n\x04Note\x12>\n\x0b\x63reate_note\x12\x17.note.CreateNoteRequest\x1a\x16.note.UserNoteResponse\x12\x36\n\tedit_note\x12\x15.note.EditNoteRequest\x1a\x12.note.BaseResponse\x12:\n\x0b\x64\x65lete_note\x12\x17.note.DeleteNoteRequest\x1a\x12.note.BaseResponse\x12G\n\x0eget_user_notes\x12\x19.note.GetUserNotesRequest\x1a\x1a.note.GetUserNotesResponseb\x06proto3')



_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
_CREATENOTEREQUEST = DESCRIPTOR.message_types_by_name['CreateNoteRequest']
_EDITNOTEREQUEST = DESCRIPTOR.message_types_by_name['EditNoteRequest']
_DELETENOTEREQUEST = DESCRIPTOR.message_types_by_name['DeleteNoteRequest']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_USERNOTERESPONSE = DESCRIPTOR.message_types_by_name['UserNoteResponse']
_GETUSERNOTESREQUEST = DESCRIPTOR.message_types_by_name['GetUserNotesRequest']
_GETUSERNOTESRESPONSE = DESCRIPTOR.message_types_by_name['GetUserNotesResponse']
BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

CreateNoteRequest = _reflection.GeneratedProtocolMessageType('CreateNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATENOTEREQUEST,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.CreateNoteRequest)
  })
_sym_db.RegisterMessage(CreateNoteRequest)

EditNoteRequest = _reflection.GeneratedProtocolMessageType('EditNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _EDITNOTEREQUEST,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.EditNoteRequest)
  })
_sym_db.RegisterMessage(EditNoteRequest)

DeleteNoteRequest = _reflection.GeneratedProtocolMessageType('DeleteNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETENOTEREQUEST,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.DeleteNoteRequest)
  })
_sym_db.RegisterMessage(DeleteNoteRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.Empty)
  })
_sym_db.RegisterMessage(Empty)

UserNoteResponse = _reflection.GeneratedProtocolMessageType('UserNoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERNOTERESPONSE,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.UserNoteResponse)
  })
_sym_db.RegisterMessage(UserNoteResponse)

GetUserNotesRequest = _reflection.GeneratedProtocolMessageType('GetUserNotesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERNOTESREQUEST,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.GetUserNotesRequest)
  })
_sym_db.RegisterMessage(GetUserNotesRequest)

GetUserNotesResponse = _reflection.GeneratedProtocolMessageType('GetUserNotesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERNOTESRESPONSE,
  '__module__' : 'protos.note_pb2'
  # @@protoc_insertion_point(class_scope:note.GetUserNotesResponse)
  })
_sym_db.RegisterMessage(GetUserNotesResponse)

_NOTE = DESCRIPTOR.services_by_name['Note']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASERESPONSE._serialized_start=27
  _BASERESPONSE._serialized_end=56
  _CREATENOTEREQUEST._serialized_start=58
  _CREATENOTEREQUEST._serialized_end=128
  _EDITNOTEREQUEST._serialized_start=130
  _EDITNOTEREQUEST._serialized_end=215
  _DELETENOTEREQUEST._serialized_start=217
  _DELETENOTEREQUEST._serialized_end=253
  _EMPTY._serialized_start=255
  _EMPTY._serialized_end=262
  _USERNOTERESPONSE._serialized_start=264
  _USERNOTERESPONSE._serialized_end=365
  _GETUSERNOTESREQUEST._serialized_start=367
  _GETUSERNOTESREQUEST._serialized_end=388
  _GETUSERNOTESRESPONSE._serialized_start=390
  _GETUSERNOTESRESPONSE._serialized_end=471
  _NOTE._serialized_start=474
  _NOTE._serialized_end=733
# @@protoc_insertion_point(module_scope)
