# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/notify_push.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/notify_push.proto\x12\x0bnotify_push\"c\n\x14RegisterTokenRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x14\n\x0c\x65nd_user_env\x18\x04 \x01(\t\"\x1d\n\x0c\x42\x61seResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"n\n\x0fPushTextRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x13\n\x0bnotify_type\x18\x03 \x01(\t\x12\x13\n\x0b\x63ustom_data\x18\x04 \x01(\t\x12\x14\n\x0cto_client_id\x18\x05 \x01(\t\"8\n\x0fPushVoipRequest\x12\x14\n\x0cto_client_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t2\xe8\x01\n\nNotifyPush\x12N\n\x0eregister_token\x12!.notify_push.RegisterTokenRequest\x1a\x19.notify_push.BaseResponse\x12\x44\n\tpush_text\x12\x1c.notify_push.PushTextRequest\x1a\x19.notify_push.BaseResponse\x12\x44\n\tpush_voip\x12\x1c.notify_push.PushVoipRequest\x1a\x19.notify_push.BaseResponseb\x06proto3')



_REGISTERTOKENREQUEST = DESCRIPTOR.message_types_by_name['RegisterTokenRequest']
_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
_PUSHTEXTREQUEST = DESCRIPTOR.message_types_by_name['PushTextRequest']
_PUSHVOIPREQUEST = DESCRIPTOR.message_types_by_name['PushVoipRequest']
RegisterTokenRequest = _reflection.GeneratedProtocolMessageType('RegisterTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERTOKENREQUEST,
  '__module__' : 'protos.notify_push_pb2'
  # @@protoc_insertion_point(class_scope:notify_push.RegisterTokenRequest)
  })
_sym_db.RegisterMessage(RegisterTokenRequest)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'protos.notify_push_pb2'
  # @@protoc_insertion_point(class_scope:notify_push.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

PushTextRequest = _reflection.GeneratedProtocolMessageType('PushTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHTEXTREQUEST,
  '__module__' : 'protos.notify_push_pb2'
  # @@protoc_insertion_point(class_scope:notify_push.PushTextRequest)
  })
_sym_db.RegisterMessage(PushTextRequest)

PushVoipRequest = _reflection.GeneratedProtocolMessageType('PushVoipRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHVOIPREQUEST,
  '__module__' : 'protos.notify_push_pb2'
  # @@protoc_insertion_point(class_scope:notify_push.PushVoipRequest)
  })
_sym_db.RegisterMessage(PushVoipRequest)

_NOTIFYPUSH = DESCRIPTOR.services_by_name['NotifyPush']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERTOKENREQUEST._serialized_start=41
  _REGISTERTOKENREQUEST._serialized_end=140
  _BASERESPONSE._serialized_start=142
  _BASERESPONSE._serialized_end=171
  _PUSHTEXTREQUEST._serialized_start=173
  _PUSHTEXTREQUEST._serialized_end=283
  _PUSHVOIPREQUEST._serialized_start=285
  _PUSHVOIPREQUEST._serialized_end=341
  _NOTIFYPUSH._serialized_start=344
  _NOTIFYPUSH._serialized_end=576
# @@protoc_insertion_point(module_scope)
