# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/server_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/server_info.proto\x12\x0bserver_info\"*\n\x0cUpdateNTSReq\x12\x0c\n\x04stun\x18\x01 \x01(\t\x12\x0c\n\x04turn\x18\x02 \x01(\t\"\x1d\n\x0c\x42\x61seResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\"\n\x11GetThreadResponse\x12\r\n\x05total\x18\x01 \x01(\x03\x32\x98\x01\n\nServerInfo\x12\x44\n\nupdate_nts\x12\x19.server_info.UpdateNTSReq\x1a\x19.server_info.BaseResponse\"\x00\x12\x44\n\x0ctotal_thread\x12\x12.server_info.Empty\x1a\x1e.server_info.GetThreadResponse\"\x00\x62\x06proto3')



_UPDATENTSREQ = DESCRIPTOR.message_types_by_name['UpdateNTSReq']
_BASERESPONSE = DESCRIPTOR.message_types_by_name['BaseResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_GETTHREADRESPONSE = DESCRIPTOR.message_types_by_name['GetThreadResponse']
UpdateNTSReq = _reflection.GeneratedProtocolMessageType('UpdateNTSReq', (_message.Message,), {
  'DESCRIPTOR' : _UPDATENTSREQ,
  '__module__' : 'protos.server_info_pb2'
  # @@protoc_insertion_point(class_scope:server_info.UpdateNTSReq)
  })
_sym_db.RegisterMessage(UpdateNTSReq)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'protos.server_info_pb2'
  # @@protoc_insertion_point(class_scope:server_info.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.server_info_pb2'
  # @@protoc_insertion_point(class_scope:server_info.Empty)
  })
_sym_db.RegisterMessage(Empty)

GetThreadResponse = _reflection.GeneratedProtocolMessageType('GetThreadResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTHREADRESPONSE,
  '__module__' : 'protos.server_info_pb2'
  # @@protoc_insertion_point(class_scope:server_info.GetThreadResponse)
  })
_sym_db.RegisterMessage(GetThreadResponse)

_SERVERINFO = DESCRIPTOR.services_by_name['ServerInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATENTSREQ._serialized_start=41
  _UPDATENTSREQ._serialized_end=83
  _BASERESPONSE._serialized_start=85
  _BASERESPONSE._serialized_end=114
  _EMPTY._serialized_start=116
  _EMPTY._serialized_end=123
  _GETTHREADRESPONSE._serialized_start=125
  _GETTHREADRESPONSE._serialized_end=159
  _SERVERINFO._serialized_start=162
  _SERVERINFO._serialized_end=314
# @@protoc_insertion_point(module_scope)
