# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/workspace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/workspace.proto',
  package='workspace',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/workspace.proto\x12\tworkspace\")\n\x08\x45rrorRes\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x0c\x42\x61seResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\x06\x65rrors\x18\x02 \x01(\x0b\x32\x13.workspace.ErrorRes\"\x81\x01\n\x17WorkspaceObjectResponse\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t\x12\x18\n\x10workspace_domain\x18\x02 \x01(\t\x12\x1c\n\x14is_default_workspace\x18\x03 \x01(\x08\x12\x18\n\x10is_own_workspace\x18\x04 \x01(\x08\"C\n\x14JoinWorkspaceRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x18\n\x10workspace_domain\x18\x02 \x01(\t\"/\n\x1aGetJoinedWorkspacesRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"X\n\x1bGetJoinedWorkspacesResponse\x12\x39\n\rlst_workspace\x18\x01 \x03(\x0b\x32\".workspace.WorkspaceObjectResponse\"A\n\x16LeaveWorkspacesRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\t2\x94\x02\n\tWorkspace\x12L\n\x0ejoin_workspace\x12\x1f.workspace.JoinWorkspaceRequest\x1a\x17.workspace.BaseResponse\"\x00\x12h\n\x15get_joined_workspaces\x12%.workspace.GetJoinedWorkspacesRequest\x1a&.workspace.GetJoinedWorkspacesResponse\"\x00\x12O\n\x0fleave_workspace\x12!.workspace.LeaveWorkspacesRequest\x1a\x17.workspace.BaseResponse\"\x00\x62\x06proto3'
)




_ERRORRES = _descriptor.Descriptor(
  name='ErrorRes',
  full_name='workspace.ErrorRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='workspace.ErrorRes.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='workspace.ErrorRes.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=78,
)


_BASERESPONSE = _descriptor.Descriptor(
  name='BaseResponse',
  full_name='workspace.BaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='workspace.BaseResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errors', full_name='workspace.BaseResponse.errors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=148,
)


_WORKSPACEOBJECTRESPONSE = _descriptor.Descriptor(
  name='WorkspaceObjectResponse',
  full_name='workspace.WorkspaceObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_id', full_name='workspace.WorkspaceObjectResponse.workspace_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workspace_domain', full_name='workspace.WorkspaceObjectResponse.workspace_domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_default_workspace', full_name='workspace.WorkspaceObjectResponse.is_default_workspace', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_own_workspace', full_name='workspace.WorkspaceObjectResponse.is_own_workspace', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=280,
)


_JOINWORKSPACEREQUEST = _descriptor.Descriptor(
  name='JoinWorkspaceRequest',
  full_name='workspace.JoinWorkspaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='workspace.JoinWorkspaceRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workspace_domain', full_name='workspace.JoinWorkspaceRequest.workspace_domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=349,
)


_GETJOINEDWORKSPACESREQUEST = _descriptor.Descriptor(
  name='GetJoinedWorkspacesRequest',
  full_name='workspace.GetJoinedWorkspacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='workspace.GetJoinedWorkspacesRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=398,
)


_GETJOINEDWORKSPACESRESPONSE = _descriptor.Descriptor(
  name='GetJoinedWorkspacesResponse',
  full_name='workspace.GetJoinedWorkspacesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lst_workspace', full_name='workspace.GetJoinedWorkspacesResponse.lst_workspace', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=488,
)


_LEAVEWORKSPACESREQUEST = _descriptor.Descriptor(
  name='LeaveWorkspacesRequest',
  full_name='workspace.LeaveWorkspacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='workspace.LeaveWorkspacesRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workspace_id', full_name='workspace.LeaveWorkspacesRequest.workspace_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=555,
)

_BASERESPONSE.fields_by_name['errors'].message_type = _ERRORRES
_GETJOINEDWORKSPACESRESPONSE.fields_by_name['lst_workspace'].message_type = _WORKSPACEOBJECTRESPONSE
DESCRIPTOR.message_types_by_name['ErrorRes'] = _ERRORRES
DESCRIPTOR.message_types_by_name['BaseResponse'] = _BASERESPONSE
DESCRIPTOR.message_types_by_name['WorkspaceObjectResponse'] = _WORKSPACEOBJECTRESPONSE
DESCRIPTOR.message_types_by_name['JoinWorkspaceRequest'] = _JOINWORKSPACEREQUEST
DESCRIPTOR.message_types_by_name['GetJoinedWorkspacesRequest'] = _GETJOINEDWORKSPACESREQUEST
DESCRIPTOR.message_types_by_name['GetJoinedWorkspacesResponse'] = _GETJOINEDWORKSPACESRESPONSE
DESCRIPTOR.message_types_by_name['LeaveWorkspacesRequest'] = _LEAVEWORKSPACESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorRes = _reflection.GeneratedProtocolMessageType('ErrorRes', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRES,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.ErrorRes)
  })
_sym_db.RegisterMessage(ErrorRes)

BaseResponse = _reflection.GeneratedProtocolMessageType('BaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASERESPONSE,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.BaseResponse)
  })
_sym_db.RegisterMessage(BaseResponse)

WorkspaceObjectResponse = _reflection.GeneratedProtocolMessageType('WorkspaceObjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _WORKSPACEOBJECTRESPONSE,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.WorkspaceObjectResponse)
  })
_sym_db.RegisterMessage(WorkspaceObjectResponse)

JoinWorkspaceRequest = _reflection.GeneratedProtocolMessageType('JoinWorkspaceRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINWORKSPACEREQUEST,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.JoinWorkspaceRequest)
  })
_sym_db.RegisterMessage(JoinWorkspaceRequest)

GetJoinedWorkspacesRequest = _reflection.GeneratedProtocolMessageType('GetJoinedWorkspacesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETJOINEDWORKSPACESREQUEST,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.GetJoinedWorkspacesRequest)
  })
_sym_db.RegisterMessage(GetJoinedWorkspacesRequest)

GetJoinedWorkspacesResponse = _reflection.GeneratedProtocolMessageType('GetJoinedWorkspacesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETJOINEDWORKSPACESRESPONSE,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.GetJoinedWorkspacesResponse)
  })
_sym_db.RegisterMessage(GetJoinedWorkspacesResponse)

LeaveWorkspacesRequest = _reflection.GeneratedProtocolMessageType('LeaveWorkspacesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEAVEWORKSPACESREQUEST,
  '__module__' : 'protos.workspace_pb2'
  # @@protoc_insertion_point(class_scope:workspace.LeaveWorkspacesRequest)
  })
_sym_db.RegisterMessage(LeaveWorkspacesRequest)



_WORKSPACE = _descriptor.ServiceDescriptor(
  name='Workspace',
  full_name='workspace.Workspace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=558,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='join_workspace',
    full_name='workspace.Workspace.join_workspace',
    index=0,
    containing_service=None,
    input_type=_JOINWORKSPACEREQUEST,
    output_type=_BASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_joined_workspaces',
    full_name='workspace.Workspace.get_joined_workspaces',
    index=1,
    containing_service=None,
    input_type=_GETJOINEDWORKSPACESREQUEST,
    output_type=_GETJOINEDWORKSPACESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='leave_workspace',
    full_name='workspace.Workspace.leave_workspace',
    index=2,
    containing_service=None,
    input_type=_LEAVEWORKSPACESREQUEST,
    output_type=_BASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKSPACE)

DESCRIPTOR.services_by_name['Workspace'] = _WORKSPACE

# @@protoc_insertion_point(module_scope)
