"""delete forekey

Revision ID: a29138e54c7a
Revises: e41522be0405
Create Date: 2021-01-06 17:59:58.295060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29138e54c7a'
down_revision = 'e41522be0405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
