"""update group

Revision ID: e41522be0405
Revises: a32c0b2387b0
Create Date: 2021-01-06 14:38:30.079880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41522be0405'
down_revision = 'a32c0b2387b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
