"""group chat

Revision ID: f98623a0ecb2
Revises: 7205029c9370
Create Date: 2021-01-06 18:09:26.644332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98623a0ecb2'
down_revision = '7205029c9370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group_chat', 'message', ['last_message_id'], ['id'])
    op.create_foreign_key(None, 'group_client_key', 'group_chat', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_client_key', type_='foreignkey')
    op.drop_constraint(None, 'group_chat', type_='foreignkey')
    # ### end Alembic commands ###
