FROM python:3.8
WORKDIR /clearkeep-backend
ENV ENV=production
COPY . ./
# setup library
RUN apt update && apt install cron -y
RUN pip install --upgrade pip
RUN pip install -r requirement.txt
RUN pip install psycopg2
# generate protobuf
RUN sh protos/gen.sh
# start application
EXPOSE 5000 5001