"""add end_user_env

Revision ID: 82cf80a9ec6a
Revises: 
Create Date: 2022-07-13 08:29:09.000802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cf80a9ec6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify_token', sa.Column('end_user_env', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify_token', 'end_user_env')
    # ### end Alembic commands ###
