# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class UserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/user.User/GetUser',
        request_serializer=proto_dot_user__pb2.UsersRequest.SerializeToString,
        response_deserializer=proto_dot_user__pb2.UserResponse.FromString,
        )
    self.GetUsers = channel.unary_unary(
        '/user.User/GetUsers',
        request_serializer=proto_dot_user__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_user__pb2.UsersResponseList.FromString,
        )


class UserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=proto_dot_user__pb2.UsersRequest.FromString,
          response_serializer=proto_dot_user__pb2.UserResponse.SerializeToString,
      ),
      'GetUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=proto_dot_user__pb2.Empty.FromString,
          response_serializer=proto_dot_user__pb2.UsersResponseList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'user.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
