# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/user.proto',
  package='user',
  syntax='proto3',
  serialized_pb=_b('\n\x10proto/user.proto\x12\x04user\" \n\x0cUsersRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\";\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"5\n\x11UsersResponseList\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.user.UserResponse2u\n\x04User\x12\x34\n\x08get_user\x12\x12.user.UsersRequest\x1a\x12.user.UserResponse\"\x00\x12\x37\n\rget_list_user\x12\x0b.user.Empty\x1a\x17.user.UsersResponseList\"\x00\x62\x06proto3')
)




_USERSREQUEST = _descriptor.Descriptor(
  name='UsersRequest',
  full_name='user.UsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='user.UsersRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=58,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='user.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=67,
)


_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='user.UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='user.UserResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='user.UserResponse.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='user.UserResponse.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=128,
)


_USERSRESPONSELIST = _descriptor.Descriptor(
  name='UsersResponseList',
  full_name='user.UsersResponseList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='user.UsersResponseList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=183,
)

_USERSRESPONSELIST.fields_by_name['list'].message_type = _USERRESPONSE
DESCRIPTOR.message_types_by_name['UsersRequest'] = _USERSREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
DESCRIPTOR.message_types_by_name['UsersResponseList'] = _USERSRESPONSELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsersRequest = _reflection.GeneratedProtocolMessageType('UsersRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERSREQUEST,
  __module__ = 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UsersRequest)
  ))
_sym_db.RegisterMessage(UsersRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.Empty)
  ))
_sym_db.RegisterMessage(Empty)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERRESPONSE,
  __module__ = 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserResponse)
  ))
_sym_db.RegisterMessage(UserResponse)

UsersResponseList = _reflection.GeneratedProtocolMessageType('UsersResponseList', (_message.Message,), dict(
  DESCRIPTOR = _USERSRESPONSELIST,
  __module__ = 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.UsersResponseList)
  ))
_sym_db.RegisterMessage(UsersResponseList)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='user.User',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=185,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_user',
    full_name='user.User.get_user',
    index=0,
    containing_service=None,
    input_type=_USERSREQUEST,
    output_type=_USERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_list_user',
    full_name='user.User.get_list_user',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_USERSRESPONSELIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class UserStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.get_user = channel.unary_unary(
          '/user.User/get_user',
          request_serializer=UsersRequest.SerializeToString,
          response_deserializer=UserResponse.FromString,
          )
      self.get_list_user = channel.unary_unary(
          '/user.User/get_list_user',
          request_serializer=Empty.SerializeToString,
          response_deserializer=UsersResponseList.FromString,
          )


  class UserServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def get_user(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def get_list_user(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'get_user': grpc.unary_unary_rpc_method_handler(
            servicer.get_user,
            request_deserializer=UsersRequest.FromString,
            response_serializer=UserResponse.SerializeToString,
        ),
        'get_list_user': grpc.unary_unary_rpc_method_handler(
            servicer.get_list_user,
            request_deserializer=Empty.FromString,
            response_serializer=UsersResponseList.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaUserServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def get_user(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def get_list_user(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaUserStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def get_user(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    get_user.future = None
    def get_list_user(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    get_list_user.future = None


  def beta_create_User_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('user.User', 'get_list_user'): Empty.FromString,
      ('user.User', 'get_user'): UsersRequest.FromString,
    }
    response_serializers = {
      ('user.User', 'get_list_user'): UsersResponseList.SerializeToString,
      ('user.User', 'get_user'): UserResponse.SerializeToString,
    }
    method_implementations = {
      ('user.User', 'get_list_user'): face_utilities.unary_unary_inline(servicer.get_list_user),
      ('user.User', 'get_user'): face_utilities.unary_unary_inline(servicer.get_user),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_User_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('user.User', 'get_list_user'): Empty.SerializeToString,
      ('user.User', 'get_user'): UsersRequest.SerializeToString,
    }
    response_deserializers = {
      ('user.User', 'get_list_user'): UsersResponseList.FromString,
      ('user.User', 'get_user'): UserResponse.FromString,
    }
    cardinalities = {
      'get_list_user': cardinality.Cardinality.UNARY_UNARY,
      'get_user': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'user.User', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
