# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_user_info = channel.unary_unary(
                '/user.User/get_user_info',
                request_serializer=proto_dot_user__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_user__pb2.UserInfoResponse.FromString,
                )
        self.update_user_info = channel.unary_unary(
                '/user.User/update_user_info',
                request_serializer=proto_dot_user__pb2.UpdateUserInfoRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.SuccessResponse.FromString,
                )
        self.change_password = channel.unary_unary(
                '/user.User/change_password',
                request_serializer=proto_dot_user__pb2.ChangePassword.SerializeToString,
                response_deserializer=proto_dot_user__pb2.SuccessResponse.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_user_info(self, request, context):
        """rpc get_user(UsersRequest) returns (UserResponse) {};
        rpc get_list_user(Empty) returns (UsersResponseList) {};
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_user_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def change_password(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_user_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_info,
                    request_deserializer=proto_dot_user__pb2.Empty.FromString,
                    response_serializer=proto_dot_user__pb2.UserInfoResponse.SerializeToString,
            ),
            'update_user_info': grpc.unary_unary_rpc_method_handler(
                    servicer.update_user_info,
                    request_deserializer=proto_dot_user__pb2.UpdateUserInfoRequest.FromString,
                    response_serializer=proto_dot_user__pb2.SuccessResponse.SerializeToString,
            ),
            'change_password': grpc.unary_unary_rpc_method_handler(
                    servicer.change_password,
                    request_deserializer=proto_dot_user__pb2.ChangePassword.FromString,
                    response_serializer=proto_dot_user__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_user_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/get_user_info',
            proto_dot_user__pb2.Empty.SerializeToString,
            proto_dot_user__pb2.UserInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_user_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/update_user_info',
            proto_dot_user__pb2.UpdateUserInfoRequest.SerializeToString,
            proto_dot_user__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def change_password(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/change_password',
            proto_dot_user__pb2.ChangePassword.SerializeToString,
            proto_dot_user__pb2.SuccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
