# Docker Compose Keycloak Postgres ( Docker compose for Keycloak with Postgres Database).
# docker-compose -f development-docker-compose.yml up -d
version: '3.1'


#volumes:
#  postgres_data:
#      driver: local

services:
#  postgres:
#      image: postgres
#      volumes:
#        - postgres_data:/var/lib/postgresql/data
#      ports:
#              - 5432:5432
#      restart: always
#      environment:
#        POSTGRES_DB: keycloak
#        POSTGRES_USER: keycloak
#        POSTGRES_PASSWORD: password
  keycloak_dev:
      image: jboss/keycloak:10.0.0
      restart: always
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak-dev
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin

      ports:
        - 18080:8080
#      depends_on:
#        - postgres
  janus_dev:
      image: phuongvmodev/janus-webrtc-gateway-docker
      restart: always
      ports:
        - 17088:7088
        - 18288:80
        - 18088:8088
        - 18188:8188