






# ` $ sudo DOCKER_BUILDKIT=1 docker-compose -f .docker/local-docker-compose-max-prod.yml up   `



# Docker Compose Keycloak Postgres ( Docker compose for Keycloak with Postgres Database).
version: '3.1'


volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      restart: always
      environment:
        POSTGRES_DB: thanhpt1_vmo_postgres_db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: clk328@2021

  prod_authen:
      image: jboss/keycloak
      restart: always
      environment:
        DB_VENDOR: POSTGRES
#        DB_ADDR: 127.0.0.1:5432 # Bao loi FATAL, failed to connect to DB
# prod_authen_1  | 09:54:57,777 FATAL [org.keycloak.services] (ServerService Thread Pool -- 65)
# Error during startup: java.lang.RuntimeException: Failed to connect to database
        DB_ADDR: postgres:5432 # Dung duoc ten services de reference IP address, ten services lam hostname
        DB_DATABASE: thanhpt1_vmo_postgres_db
        DB_USER: admin
        DB_PASSWORD: clk328@2021
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: clk328@2021
        KEYCLOAK_LOGLEVEL: ALL
        JAVA_TOOL_OPTIONS: -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled
        command: -b 0.0.0.0 -bmanagement 0.0.0.0

      ports:
        - 8080:8080
        - 9990:9990
      depends_on:
        - postgres
  prod_webrtc:
      image: phuongvmodev/janus-webrtc-gateway-docker
      restart: always
      ports:
        - 7088:7088
        - 8288:80
        - 8088:8088
        - 8188:8188



#  main_module:
#    build:
#      context: ..
#      dockerfile: .docker/clearkeep-main-module.dockerfile
#
#    # Mapping of container port to host
#    ports:
#      - 25000:25000
#      - 25001:25001
#    # Mount volume
#    volumes:
#      - ../:/clearkeep-main-module-source
#
#    # Link database container to app container
#    # for reachability.
#    links:
#      - postgres:5432
#    depends_on:
#      - postgres
