name: clearkeep-test

on:
  push:
    branches: [ production ]
jobs:
  deploy-production:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
   
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

     - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v1

     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./.docker/local/dockerfile_product
         push: true
         tags: hoppham1210/ck:grpc-clk328

     - name: ssh server and run script
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST_PRODUCT }}
         username: ${{ secrets.USERNAME_PRODUCT }}
         key: ${{ secrets.KEY_PRODUCT }}
         port: ${{ secrets.PORT_PRODUCT }}
         script: sh prod-clk328/grpc/run.sh

    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}

    #- name: Run app
    #  uses: JimCronqvist/action-ssh@master
    #  with:
    #    hosts: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
    #    privateKey: ${{ secrets.KEY }}
    #    command: |
    #      cd /home/ubuntu/prod-clk328/ck-backend
    #      git checkout production
    #      git reset --hard HEAD
    #      git pull
    #      pip3 install -r requirement.txt
    #      python3 -m grpc_tools.protoc -I=. protos/*.proto --python_out=. --grpc_python_out=.
    #      sudo systemctl restart prod-http-clk328.service
    #      sleep 10
    #      sudo systemctl restart prod-grpc-clk328.service
    #      sleep 20
    #      python3 cron_tab.py
    #      sleep 20
    #      sudo systemctl restart dev-http-clk328.service
    #      sudo systemctl restart stagging-http-clk328.service
    #      docker restart clearkeep
    #      ./restart-service.sh